modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="test"
version="1.0.0"
displayName="test"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="AuraRumeur_Zbs, MCreator"

[[dependencies.test]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



